/*
 * Order Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type GetOrder struct {
	Id string `json:"id"`

	OrderedAtTimestamp int32 `json:"orderedAtTimestamp"`

	// RUB
	Cost int32 `json:"cost"`

	MenuItems []MenuItem `json:"menuItems"`
}
