SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `order`;
CREATE TABLE `order`
(
    id VARCHAR(37) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS menu_item;
CREATE TABLE menu_item
(
    id       VARCHAR(37)  NOT NULL,
    order_id VARCHAR(37)  NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    cost     DECIMAL(10, 2),
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE ON UPDATE CASCADE
);
SET FOREIGN_KEY_CHECKS=1;